name: Release Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      force_latest:
        description: 'Force update latest version'
        required: true
        type: boolean
        default: true

permissions:
  contents: write  # Add write permission for releases

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get latest version
        id: latest_version
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
      
      - name: Set version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ steps.latest_version.outputs.tag }}"
          else
            VERSION="${{ github.ref_name }}"
          fi
          echo "value=$VERSION" >> $GITHUB_OUTPUT
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Validate tag format
        run: |
          if [[ ! $RELEASE_VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format. Must be in format v1.2.3"
            exit 1
          fi
      
      - name: Check version match
        run: |
          VERSION=${RELEASE_VERSION#v}
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$VERSION" != "$PKG_VERSION" ]; then
            echo "Version mismatch: Release version ($VERSION) does not match package.json version ($PKG_VERSION)"
            exit 1
          fi
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Prepare build directory
        shell: bash
        run: |
          rm -rf build
          mkdir -p build
        
      - name: Install vsce
        run: npm install -g @vscode/vsce
        
      - name: Package extension
        shell: bash
        run: vsce package -o "build/thymelab-vscode-${RELEASE_VERSION#v}.vsix"

      - name: Get Changes
        id: get_changes
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            # If no previous tag exists, get all commits
            CHANGES=$(git log --pretty=format:"- %s")
          else
            # Get commits between tags
            CHANGES=$(git log --pretty=format:"- %s" ${PREV_TAG}..HEAD)
          fi
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.force_latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/thymelab-vscode-*.vsix
          generate_release_notes: true
          name: ThymeLab VSCode ${{ steps.version.outputs.value }}
          tag_name: ${{ steps.version.outputs.value }}
          body: |
            ## ThymeLab VSCode Extension ${{ steps.version.outputs.value }}

            ### Installation Instructions

            #### Method 1: Install from VSIX
            1. Download the `thymelab-vscode-${{ steps.version.outputs.value }}.vsix` file from this release
            2. Open VS Code
            3. Go to Extensions view (Ctrl+Shift+X)
            4. Click on the '...' menu (Views and More Actions)
            5. Select 'Install from VSIX...'
            6. Choose the downloaded VSIX file

            #### Method 2: Command Line Installation
            ```bash
            code --install-extension thymelab-vscode-${{ steps.version.outputs.value }}.vsix
            ```

            ### What's Changed
            ${{ steps.get_changes.outputs.changes }} 